controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    command_interfaces:
      - position
      - velocity

    state_interfaces:
      - position
      - velocity

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

gripper_controller:
  ros__parameters:
    joints:
      - robotiq_85_left_knuckle_joint
      
    command_interfaces:
      - position

    state_interfaces:
        - position
        - velocity

    open_loop_control: true
    allow_integration_in_goal_trajectories: true