robotiq_85_left_finger_joint:
    has_velocity_limits: false
    max_velocity: 100.00
    has_acceleration_limits: false

robotiq_85_right_finger_joint:
    has_velocity_limits: true
    max_velocity: 100.00
    has_acceleration_limits: false
    max_acceleration: 0